if (ANDROID AND NOT DEFINED ION_ANDROID_THIRD_PARTY_DIR)
  if (DEFINED ENV{ANDROID_NDK_ROOT})
    set(ION_ANDROID_NDK_ROOT "$ENV{ANDROID_NDK_ROOT}")
  elseif (ANDROID_NDK)
    set(ION_ANDROID_NDK_ROOT "${ANDROID_NDK}")
  elseif (CMAKE_ANDROID_NDK)
    set(ION_ANDROID_NDK_ROOT "${CMAKE_ANDROID_NDK}")
  else()
    message(FATAL_ERROR "ANDROID_NDK_ROOT is not set (and ANDROID_NDK/CMAKE_ANDROID_NDK not provided).")
  endif()

  if (DEFINED ANDROID_ABI)
    set(ION_ANDROID_ABI "${ANDROID_ABI}")
  elseif (DEFINED CMAKE_ANDROID_ARCH_ABI)
    set(ION_ANDROID_ABI "${CMAKE_ANDROID_ARCH_ABI}")
  else()
    message(FATAL_ERROR "ANDROID_ABI is not set; pass -DANDROID_ABI or use Android toolchain.")
  endif()

  set(ION_ANDROID_THIRD_PARTY_DIR "${CMAKE_CURRENT_BINARY_DIR}/android/third_party")

  if (ION_ANDROID_ABI STREQUAL "armeabi-v7a")
    set(ION_ANDROID_ARCH "arm")
    set(ION_ANDROID_ARCH_DIR "armv7")
    set(ION_ANDROID_SODIUM_DIR "libsodium-android-armv7-a")
    set(ION_ANDROID_OPENSSL_DIR "arm")
    set(ION_ANDROID_HOST "arm-linux-androideabi")
    set(ION_ANDROID_CLANG_PREFIX "armv7a-linux-androideabi")
  elseif (ION_ANDROID_ABI STREQUAL "arm64-v8a")
    set(ION_ANDROID_ARCH "arm64")
    set(ION_ANDROID_ARCH_DIR "armv8")
    set(ION_ANDROID_SODIUM_DIR "libsodium-android-armv8-a")
    set(ION_ANDROID_OPENSSL_DIR "arm64")
    set(ION_ANDROID_HOST "aarch64-linux-android")
    set(ION_ANDROID_CLANG_PREFIX "aarch64-linux-android")
  elseif (ION_ANDROID_ABI STREQUAL "x86")
    set(ION_ANDROID_ARCH "x86")
    set(ION_ANDROID_ARCH_DIR "i686")
    set(ION_ANDROID_SODIUM_DIR "libsodium-android-i686")
    set(ION_ANDROID_OPENSSL_DIR "x86")
    set(ION_ANDROID_HOST "i686-linux-android")
    set(ION_ANDROID_CLANG_PREFIX "i686-linux-android")
  elseif (ION_ANDROID_ABI STREQUAL "x86_64")
    set(ION_ANDROID_ARCH "x86_64")
    set(ION_ANDROID_ARCH_DIR "x86-64")
    set(ION_ANDROID_SODIUM_DIR "libsodium-android-westmere")
    set(ION_ANDROID_OPENSSL_DIR "x86_64")
    set(ION_ANDROID_HOST "x86_64-linux-android")
    set(ION_ANDROID_CLANG_PREFIX "x86_64-linux-android")
  else()
    message(FATAL_ERROR "Unsupported ANDROID_ABI: ${ION_ANDROID_ABI}")
  endif()

  if (CMAKE_ANDROID_API)
    set(ION_ANDROID_API "${CMAKE_ANDROID_API}")
  elseif (ANDROID_PLATFORM)
    string(REGEX REPLACE "android-" "" ION_ANDROID_API "${ANDROID_PLATFORM}")
  elseif (ANDROID_NATIVE_API_LEVEL)
    set(ION_ANDROID_API "${ANDROID_NATIVE_API_LEVEL}")
  else()
    set(ION_ANDROID_API "21")
  endif()

  set(ION_ANDROID_NDK_PREBUILT_DIR "${ION_ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt")
  set(ION_ANDROID_NDK_BIN "")
  set(ION_ANDROID_HOST_TAG "")
  set(_ion_host_arch "")
  if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
    set(_ion_host_arch "arm64")
  elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
    set(_ion_host_arch "x86_64")
  elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^i.86$")
    set(_ion_host_arch "x86")
  endif()

  set(_ion_host_tag_candidates "")
  if (WIN32)
    list(APPEND _ion_host_tag_candidates "windows-x86_64" "windows")
  elseif (APPLE)
    if (_ion_host_arch STREQUAL "arm64")
      list(APPEND _ion_host_tag_candidates "darwin-arm64" "darwin-x86_64")
    else()
      list(APPEND _ion_host_tag_candidates "darwin-x86_64" "darwin-arm64")
    endif()
  else()
    if (_ion_host_arch STREQUAL "arm64")
      list(APPEND _ion_host_tag_candidates "linux-arm64" "linux-aarch64" "linux-x86_64")
    else()
      list(APPEND _ion_host_tag_candidates "linux-x86_64")
    endif()
  endif()

  foreach(_ion_host_tag IN LISTS _ion_host_tag_candidates)
    if (EXISTS "${ION_ANDROID_NDK_PREBUILT_DIR}/${_ion_host_tag}/bin")
      set(ION_ANDROID_NDK_BIN "${ION_ANDROID_NDK_PREBUILT_DIR}/${_ion_host_tag}/bin")
      set(ION_ANDROID_HOST_TAG "${_ion_host_tag}")
      break()
    endif()
  endforeach()

  if (ION_ANDROID_NDK_BIN STREQUAL "")
    file(GLOB _ion_ndk_bins "${ION_ANDROID_NDK_PREBUILT_DIR}/*/bin")
    list(LENGTH _ion_ndk_bins _ion_ndk_bins_len)
    if (_ion_ndk_bins_len GREATER 0)
      list(GET _ion_ndk_bins 0 ION_ANDROID_NDK_BIN)
      get_filename_component(_ion_host_tag_dir "${ION_ANDROID_NDK_BIN}" DIRECTORY)
      get_filename_component(ION_ANDROID_HOST_TAG "${_ion_host_tag_dir}" NAME)
    endif()
  endif()

  if (ION_ANDROID_NDK_BIN STREQUAL "")
    message(FATAL_ERROR "Android NDK bin path not found under ${ION_ANDROID_NDK_PREBUILT_DIR}.")
  endif()

  set(ION_ANDROID_CC "${ION_ANDROID_NDK_BIN}/${ION_ANDROID_CLANG_PREFIX}${ION_ANDROID_API}-clang")
  if (NOT EXISTS "${ION_ANDROID_CC}")
    file(GLOB ION_ANDROID_CLANG_CANDIDATES
      "${ION_ANDROID_NDK_BIN}/${ION_ANDROID_CLANG_PREFIX}[0-9]*-clang")
    set(ION_ANDROID_CLANG_MAX "")
    foreach(ION_ANDROID_CLANG_CANDIDATE IN LISTS ION_ANDROID_CLANG_CANDIDATES)
      get_filename_component(ION_ANDROID_CLANG_FILE "${ION_ANDROID_CLANG_CANDIDATE}" NAME)
      string(REGEX REPLACE "^${ION_ANDROID_CLANG_PREFIX}([0-9]+)-clang$" "\\1"
        ION_ANDROID_CLANG_VER "${ION_ANDROID_CLANG_FILE}")
      if (ION_ANDROID_CLANG_VER MATCHES "^[0-9]+$")
        if (ION_ANDROID_CLANG_MAX STREQUAL "" OR ION_ANDROID_CLANG_VER GREATER ION_ANDROID_CLANG_MAX)
          set(ION_ANDROID_CLANG_MAX "${ION_ANDROID_CLANG_VER}")
        endif()
      endif()
    endforeach()
    if (ION_ANDROID_CLANG_MAX STREQUAL "")
      message(FATAL_ERROR "No NDK clang found for ${ION_ANDROID_CLANG_PREFIX} under ${ION_ANDROID_NDK_BIN}.")
    endif()
    message(STATUS "Requested Android API ${ION_ANDROID_API} not available for ${ION_ANDROID_ABI}; falling back to ${ION_ANDROID_CLANG_MAX}.")
    set(ION_ANDROID_API "${ION_ANDROID_CLANG_MAX}")
    set(ION_ANDROID_CC "${ION_ANDROID_NDK_BIN}/${ION_ANDROID_CLANG_PREFIX}${ION_ANDROID_API}-clang")
  endif()

  set(ION_ANDROID_CC "${ION_ANDROID_NDK_BIN}/${ION_ANDROID_CLANG_PREFIX}${ION_ANDROID_API}-clang")
  set(ION_ANDROID_CXX "${ION_ANDROID_NDK_BIN}/${ION_ANDROID_CLANG_PREFIX}${ION_ANDROID_API}-clang++")
  set(ION_ANDROID_AR "${ION_ANDROID_NDK_BIN}/llvm-ar")
  set(ION_ANDROID_RANLIB "${ION_ANDROID_NDK_BIN}/llvm-ranlib")
  set(ION_ANDROID_NM "${ION_ANDROID_NDK_BIN}/llvm-nm")

  message(STATUS "Android third_party dir: ${ION_ANDROID_THIRD_PARTY_DIR} (ABI=${ION_ANDROID_ABI}, API=${ION_ANDROID_API})")
endif()
